lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-minimal

title: Anastasiia Beskina's homepage
description: Hi, my name is Anastasiia and here I write about my academic work.

social_links:
  - name: ORCID
    url: https://orcid.org/0000-0002-3165-6788
  - name: Scopus
    url: https://www.scopus.com/authid/detail.uri?authorId=58861088900
  - name: Google Scholar
    url: https://scholar.google.com/citations?hl=uk&user=GwBTM6YAAAAJ
  - name: ResearchGate
    url: https://www.researchgate.net/profile/Anastasiia-Breskina
