lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-merlot
title: Anastasiia's homepage
description: Hi, my name is Anastasiia and here I write about my academic work.