lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: jekyll-theme-minimal
title: Anastasiia Beskina's homepage
description: Hi, my name is Anastasiia and here I write about my academic work.
[ORCID, https://orcid.org/0000-0002-3165-6788]
[Scopus, https://www.scopus.com/authid/detail.uri?authorId=58861088900]
[Google Scholar, https://scholar.google.com/citations?hl=uk&user=GwBTM6YAAAAJ]
[ResearchGate, https://www.researchgate.net/profile/Anastasiia-Breskina]
